/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIWorkspace */

#ifndef _Included_JNIWorkspace
#define _Included_JNIWorkspace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIWorkspace
 * Method:    initWorkspace
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JNIWorkspace_initWorkspace
  (JNIEnv *, jobject);

/*
 * Class:     JNIWorkspace
 * Method:    deleteWorkspace
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JNIWorkspace_deleteWorkspace
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JNIWorkspace
 * Method:    newMatrix
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNIWorkspace_newMatrix
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     JNIWorkspace
 * Method:    findMatrix
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIWorkspace_findMatrix
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     JNIWorkspace
 * Method:    updateMatrix
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNIWorkspace_updateMatrix
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     JNIWorkspace
 * Method:    deleteMatrix
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNIWorkspace_deleteMatrix
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     JNIWorkspace
 * Method:    resolveExpression
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIWorkspace_resolveExpression
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
